package com.ispcustomerportal.entity;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents a subscription in the system.
 * 
 * This entity maps to the 'subscriptions' table in the database and holds information about
 * a customer's subscription to an internet plan.
 */
@Entity
@Table(name = "subscriptions")
public class Subscription {

    /**
     * The unique identifier for the subscription.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The date when the subscription was activated.
     */
    @Column(name = "activation_date")
    private LocalDateTime activationDate;

    /**
     * The date when the subscription will expire.
     */
    @Column(name = "expiry_date")
    private LocalDateTime expiryDate;

    /**
     * The current status of the subscription (e.g., active, inactive).
     */
    @Column(name = "status")
    private String status;

    /**
     * The date and time when the subscription record was created.
     * Automatically set when the record is created.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * The date and time when the subscription record was last updated.
     * Automatically set when the record is updated.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * The customer associated with this subscription.
     */
    @ManyToOne
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /**
     * The internet plan associated with this subscription.
     */
    @ManyToOne
    @JoinColumn(name = "internet_plan_id", nullable = false)
    private InternetPlan internetPlan;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getActivationDate() {
        return activationDate;
    }

    public void setActivationDate(LocalDateTime activationDate) {
        this.activationDate = activationDate;
    }

    public LocalDateTime getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public InternetPlan getInternetPlan() {
        return internetPlan;
    }

    public void setInternetPlan(InternetPlan internetPlan) {
        this.internetPlan = internetPlan;
    }
}