package com.ispcustomerportal.entity;

import javax.persistence.*;  
import java.time.LocalDateTime;  

/**  
 * User is an entity class representing a user in the system.  
 * It is mapped to the 'users' table in the database.  
 */  
@Entity  
@Table(name = "users")  
public class User {

    /**  
     * Unique identifier for the user.  
     * This field is the primary key and is auto-generated by the database.  
     */  
    @Id  
    @GeneratedValue(strategy = GenerationType.IDENTITY)  
    private Long id;

    /**  
     * Username of the user, which must be unique.  
     * This field is used for login purposes.  
     */  
    @Column(nullable = false, unique = true)  
    private String username;

    /**  
     * Email address of the user.  
     * This field must be unique and is used for notifications and communication.  
     */  
    @Column(nullable = false, unique = true)  
    private String email;

    /**  
     * Password for the user's account.  
     * This field should be stored in a secure manner (hashed) for security purposes.  
     */  
    @Column(nullable = false)  
    private String password;

    /**  
     * Role of the user in the system, indicating their level of access.  
     * This could be 'USER', 'ADMIN', etc.  
     */  
    @Column(nullable = false)  
    private String role;

    /**  
     * Timestamp indicating when the user was created.  
     * This field is automatically set when the user is created.  
     */  
    @Column(name = "created_at", updatable = false)  
    private LocalDateTime createdAt;

    /**  
     * Timestamp indicating the last time the user was updated.  
     * This field is automatically updated whenever the user information is modified.  
     */  
    @Column(name = "updated_at")  
    private LocalDateTime updatedAt;

    // Getters and Setters  

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
